apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base/simple
patchesJson6902:
- target:
    group: batch
    version: v1beta1
    kind: CronJob
    name: cronjob1
  path: ./patch.yaml